# Form implementation generated from reading ui file 'c:\Users\jordi\Desktop\MongoBD\MongoDB\Vistes\Pacient.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Roles(object):
    def setupUi(self, Roles):
        Roles.setObjectName("Roles")
        Roles.resize(678, 513)
        Roles.setStyleSheet("\n"
"QWidget#centralwidget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.228856 rgba(223, 0, 255, 255), stop:0.761194 rgba(0, 186, 224, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=Roles)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tenca = QtWidgets.QPushButton(parent=self.centralwidget)
        self.tenca.setStyleSheet("border-radius:10px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(72, 201, 176);")
        self.tenca.setObjectName("tenca")
        self.gridLayout.addWidget(self.tenca, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.DemanarHora = QtWidgets.QWidget()
        self.DemanarHora.setObjectName("DemanarHora")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.DemanarHora)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox = QtWidgets.QComboBox(parent=self.DemanarHora)
        self.comboBox.setStyleSheet("border-radius:10px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(72, 201, 176);")
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 7, 1, 1, 5)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.DemanarHora)
        self.comboBox_2.setStyleSheet("border-radius:10px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(72, 201, 176);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_2.addWidget(self.comboBox_2, 12, 1, 1, 5)
        self.llista_metges = QtWidgets.QComboBox(parent=self.DemanarHora)
        self.llista_metges.setStyleSheet("border-radius:10px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(72, 201, 176);")
        self.llista_metges.setObjectName("llista_metges")
        self.gridLayout_2.addWidget(self.llista_metges, 4, 1, 1, 5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 4, 6, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.DemanarHora)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 6, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.DemanarHora)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.DemanarHora)
        self.pushButton.setStyleSheet("border-radius:10px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(72, 201, 176);")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 16, 5, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 5, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 16, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 8, 5, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.DemanarHora)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 9, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 4, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 0, 2, 1, 1)
        self.usuari = QtWidgets.QLabel(parent=self.DemanarHora)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.usuari.setFont(font)
        self.usuari.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: black;")
        self.usuari.setObjectName("usuari")
        self.gridLayout_2.addWidget(self.usuari, 0, 0, 1, 1)
        self.error = QtWidgets.QLabel(parent=self.DemanarHora)
        self.error.setText("")
        self.error.setObjectName("error")
        self.gridLayout_2.addWidget(self.error, 14, 0, 1, 4)
        self.tabWidget.addTab(self.DemanarHora, "")
        self.ConsultaVisites = QtWidgets.QWidget()
        self.ConsultaVisites.setObjectName("ConsultaVisites")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ConsultaVisites)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.usuari_2 = QtWidgets.QLabel(parent=self.ConsultaVisites)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.usuari_2.setFont(font)
        self.usuari_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: Black;")
        self.usuari_2.setObjectName("usuari_2")
        self.gridLayout_3.addWidget(self.usuari_2, 0, 0, 1, 1)
        self.error_2 = QtWidgets.QLabel(parent=self.ConsultaVisites)
        self.error_2.setText("")
        self.error_2.setObjectName("error_2")
        self.gridLayout_3.addWidget(self.error_2, 2, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.ConsultaVisites)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.tabWidget.addTab(self.ConsultaVisites, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 2)
        Roles.setCentralWidget(self.centralwidget)

        self.retranslateUi(Roles)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Roles)

    def retranslateUi(self, Roles):
        _translate = QtCore.QCoreApplication.translate
        Roles.setWindowTitle(_translate("Roles", "Pacient"))
        self.tenca.setText(_translate("Roles", "Tancar Sessió"))
        self.label_3.setWhatsThis(_translate("Roles", "<html><head/><body><p><br/></p></body></html>"))
        self.label_3.setText(_translate("Roles", "Dia"))
        self.label_2.setText(_translate("Roles", "Metges"))
        self.pushButton.setText(_translate("Roles", "Demanar"))
        self.label.setText(_translate("Roles", "Hora"))
        self.usuari.setText(_translate("Roles", "<html><head/><body><p>sa</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DemanarHora), _translate("Roles", "Demanar Hora"))
        self.usuari_2.setText(_translate("Roles", "<html><head/><body><p>sa</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ConsultaVisites), _translate("Roles", "Consulta Visites"))
