# Form implementation generated from reading ui file 'c:\Users\jordi\Desktop\MongoBD\MongoDB\Vistes\restablir_contra.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(597, 412)
        Login.setStyleSheet("\n"
"QWidget#centralwidget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0.228856 rgba(223, 0, 255, 255), stop:0.761194 rgba(0, 186, 224, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=Login)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 9, 1, 1, 1)
        self.contra1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.contra1.setStyleSheet("border-radius:10px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(176, 176, 176);")
        self.contra1.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.contra1.setObjectName("contra1")
        self.gridLayout.addWidget(self.contra1, 3, 2, 1, 1)
        self.contra = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.contra.setStyleSheet("border-radius:10px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(176, 176, 176);")
        self.contra.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.contra.setObjectName("contra")
        self.gridLayout.addWidget(self.contra, 1, 2, 1, 1)
        self.usuari_2 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.usuari_2.setFont(font)
        self.usuari_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: white;")
        self.usuari_2.setObjectName("usuari_2")
        self.gridLayout.addWidget(self.usuari_2, 0, 2, 1, 2)
        self.usuari = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.usuari.setFont(font)
        self.usuari.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: white;")
        self.usuari.setObjectName("usuari")
        self.gridLayout.addWidget(self.usuari, 0, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setStyleSheet("border-radius:10px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(72, 201, 176);")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 9, 2, 1, 1)
        self.contra2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.contra2.setStyleSheet("border-radius:10px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(176, 176, 176);")
        self.contra2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.contra2.setObjectName("contra2")
        self.gridLayout.addWidget(self.contra2, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: white;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: white;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: white;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setStyleSheet("border-radius:10px;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(72, 201, 176);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 9, 0, 1, 1)
        self.errorcontra = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.errorcontra.setFont(font)
        self.errorcontra.setObjectName("errorcontra")
        self.gridLayout.addWidget(self.errorcontra, 6, 1, 1, 2)
        Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)
        Login.setTabOrder(self.contra, self.contra1)
        Login.setTabOrder(self.contra1, self.contra2)
        Login.setTabOrder(self.contra2, self.pushButton)
        Login.setTabOrder(self.pushButton, self.pushButton_2)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.usuari_2.setText(_translate("Login", "<html><head/><body><p>Cambiar contrasenya </p></body></html>"))
        self.usuari.setText(_translate("Login", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton.setText(_translate("Login", "Crear"))
        self.label_2.setText(_translate("Login", "<html><head/><body><p><span style=\" font-size:10pt;\">Torna a escriure la</span></p><p><span style=\" font-size:10pt;\">Contrasenya:</span></p></body></html>"))
        self.label.setText(_translate("Login", "<html><head/><body><p><span style=\" font-size:10pt;\">Nova Contrasenya:</span></p></body></html>"))
        self.label_3.setText(_translate("Login", "<html><head/><body><p><span style=\" font-size:10pt;\">Contrasenya Actual:</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Login", "Back"))
        self.errorcontra.setText(_translate("Login", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
